resources:
  - job.yaml

configMapGenerator:
  - name: openbao-policies
    files:
      - ../policies/ci.hcl
      - ../policies/argo.hcl
      - ../policies/config.hcl
      - ../policies/external-secrets.hcl

generatorOptions:
  disableNameSuffixHash: true
