resources:
  - job.yaml

configMapGenerator:
  - name: openbao-policies
    files:
      - ../policies/ci.hcl
      - ../policies/argo.hcl
      - ../policies/config.hcl
      - ../policies/external-secrets.hcl
      - ../policies/apprise.hcl
      - ../policies/cloudflared.hcl
      - ../policies/external-dns.hcl
      - ../policies/ansible-runner.hcl
      - ../policies/homepage.hcl
      - ../policies/grafana.hcl
      - ../policies/authentik.hcl
      - ../policies/gitea.hcl

generatorOptions:
  disableNameSuffixHash: true
