apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-grafana-desired
  namespace: observability
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: homepage-grafana-desired
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: username
      remoteRef:
        key: apps/homepage/grafana
        property: username
    - secretKey: password
      remoteRef:
        key: apps/homepage/grafana
        property: password
