apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-push-mirror
  namespace: gitea
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: gitea-push-mirror
    creationPolicy: Orphan
    deletionPolicy: Retain
  data:
    - secretKey: remote_url
      remoteRef:
        key: apps/gitea/push-mirror
        property: remote_url
    - secretKey: username
      remoteRef:
        key: apps/gitea/push-mirror
        property: username
    - secretKey: token
      remoteRef:
        key: apps/gitea/push-mirror
        property: token
