apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-actions-runner
  namespace: gitea
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: gitea-actions-runner
    creationPolicy: Orphan
    deletionPolicy: Retain
  data:
    - secretKey: token
      remoteRef:
        key: apps/gitea/actions-runner
        property: token
