apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-cluster-config
data:
  GITEA_LOCAL_HOST: 'gitea.adaetum.local'
  ARGOCD_LOCAL_HOST: 'argocd.adaetum.local'
  HOMEPAGE_LOCAL_HOST: 'home.adaetum.local'
  HOMEPAGE_PUBLIC_HOST: 'home.adaetum.invalid'
  HOMEPAGE_ALLOWED_HOSTS: 'home.adaetum.local,home.adaetum.invalid,homepage.homepage.svc.cluster.local,homepage.homepage.svc,localhost,127.0.0.1'
  OPENBAO_LOCAL_HOST: 'openbao.adaetum.local'
  OPENBAO_PUBLIC_HOST: 'openbao.adaetum.invalid'
  AUTHENTIK_LOCAL_HOST: 'authentik.adaetum.local'
  AUTHENTIK_PUBLIC_HOST: 'authentik.adaetum.invalid'
  HEADLAMP_LOCAL_HOST: 'headlamp.adaetum.local'
  HEADLAMP_PUBLIC_HOST: 'headlamp.adaetum.invalid'
  ALERTMANAGER_LOCAL_HOST: 'alertmanager.adaetum.local'
  ALERTMANAGER_PUBLIC_HOST: 'alertmanager.adaetum.invalid'
  GRAFANA_LOCAL_HOST: 'grafana.adaetum.local'
  GRAFANA_PUBLIC_HOST: 'grafana.adaetum.invalid'
  PROMETHEUS_LOCAL_HOST: 'prometheus.adaetum.local'
  PROMETHEUS_PUBLIC_HOST: 'prometheus.adaetum.invalid'
  REGISTRY_PUBLIC_HOST: 'registry.adaetum.invalid'
  RANCHER_PUBLIC_HOST: 'rancher.adaetum.invalid'
