apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-cluster-config
data:
  GITEA_LOCAL_HOST: 'gitea.example.local'
  ARGOCD_LOCAL_HOST: 'argocd.example.local'
  HOMEPAGE_LOCAL_HOST: 'home.example.local'
  HOMEPAGE_PUBLIC_HOST: 'home.example.services'
  HOMEPAGE_ALLOWED_HOSTS: 'home.example.local,home.example.services,homepage.homepage.svc.cluster.local,homepage.homepage.svc,localhost,127.0.0.1'
  OPENBAO_LOCAL_HOST: 'openbao.example.local'
  OPENBAO_PUBLIC_HOST: 'openbao.example.services'
  AUTHENTIK_LOCAL_HOST: 'authentik.example.local'
  AUTHENTIK_PUBLIC_HOST: 'authentik.example.services'
  HEADLAMP_LOCAL_HOST: 'headlamp.example.local'
  HEADLAMP_PUBLIC_HOST: 'headlamp.example.services'
  ALERTMANAGER_LOCAL_HOST: 'alertmanager.example.local'
  ALERTMANAGER_PUBLIC_HOST: 'alertmanager.example.services'
  GRAFANA_LOCAL_HOST: 'grafana.example.local'
  GRAFANA_PUBLIC_HOST: 'grafana.example.services'
  PROMETHEUS_LOCAL_HOST: 'prometheus.example.local'
  PROMETHEUS_PUBLIC_HOST: 'prometheus.example.services'
  REGISTRY_PUBLIC_HOST: 'registry.example.services'
  RANCHER_PUBLIC_HOST: 'rancher.example.services'
