apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-cluster-config
data:
  GITEA_LOCAL_HOST: 'gitea.mudazukai.cloud.local'
  ARGOCD_LOCAL_HOST: 'argocd.mudazukai.cloud.local'
  HOMEPAGE_LOCAL_HOST: 'home.mudazukai.cloud.local'
  HOMEPAGE_PUBLIC_HOST: 'home.mudazukai.cloud'
  HOMEPAGE_ALLOWED_HOSTS: 'home.mudazukai.cloud.local,home.mudazukai.cloud,homepage.homepage.svc.cluster.local,homepage.homepage.svc,localhost,127.0.0.1'
  OPENBAO_LOCAL_HOST: 'openbao.mudazukai.cloud.local'
  OPENBAO_PUBLIC_HOST: 'openbao.mudazukai.cloud'
  AUTHENTIK_LOCAL_HOST: 'authentik.mudazukai.cloud.local'
  AUTHENTIK_PUBLIC_HOST: 'authentik.mudazukai.cloud'
  HEADLAMP_LOCAL_HOST: 'headlamp.mudazukai.cloud.local'
  HEADLAMP_PUBLIC_HOST: 'headlamp.mudazukai.cloud'
  ALERTMANAGER_LOCAL_HOST: 'alertmanager.mudazukai.cloud.local'
  ALERTMANAGER_PUBLIC_HOST: 'alertmanager.mudazukai.cloud'
  GRAFANA_LOCAL_HOST: 'grafana.mudazukai.cloud.local'
  GRAFANA_PUBLIC_HOST: 'grafana.mudazukai.cloud'
  PROMETHEUS_LOCAL_HOST: 'prometheus.mudazukai.cloud.local'
  PROMETHEUS_PUBLIC_HOST: 'prometheus.mudazukai.cloud'
  REGISTRY_PUBLIC_HOST: 'registry.mudazukai.cloud'
  RANCHER_PUBLIC_HOST: 'rancher.mudazukai.cloud'
