apiVersion: v1
kind: ServiceAccount
metadata:
  name: ntfy
  namespace: observability
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ntfy-openbao
  namespace: observability
spec:
  provider: openbao
  parameters:
    roleName: ntfy
    objects: |
      - objectName: admin-password
        secretPath: secret/data/apps/observability/ntfy
        secretKey: admin_password
      - objectName: apprise-password
        secretPath: secret/data/apps/observability/ntfy
        secretKey: apprise_password
