apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openbao
  namespace: openbao
spec:
  serviceName: openbao-internal
  replicas: 1
  selector:
    matchLabels:
      app: openbao
  template:
    metadata:
      labels:
        app: openbao
    spec:
      initContainers:
        - name: openbao-config-sync
          image: busybox:1.38.0@sha256:fd8d9aa63ba2f0982b5304e1ee8d3b90a210bc1ffb5314d980eb6962f1a9715d
          command:
            - sh
            - -c
            - |
              set -e
              mkdir -p /openbao/config
              rm -rf /openbao/config/*
              cp -L /openbao/config-ro/* /openbao/config/
              chown -R 1000:1000 /openbao/config || true
              find /openbao/config -type d -exec chmod 0750 {} +
              find /openbao/config -type f -exec chmod 0640 {} +
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
            - name: openbao-config
              mountPath: /openbao/config-ro
              readOnly: true
            - name: openbao-config-rw
              mountPath: /openbao/config
        - name: openbao-perms
          image: busybox:1.38.0@sha256:fd8d9aa63ba2f0982b5304e1ee8d3b90a210bc1ffb5314d980eb6962f1a9715d
          command:
            - sh
            - -c
            - |
              set -e
              mkdir -p /openbao/data
              chown -R 1000:1000 /openbao/data || true
              chmod -R 0777 /openbao/data
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
            - name: openbao-data
              mountPath: /openbao/data
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: Always
      serviceAccountName: openbao
      containers:
        - name: openbao
          image: ghcr.io/openbao/openbao:2.6.1@sha256:5b2486ab0fb90bbc788cc345b0a08616dfb375873ee8be5df3a2fd4d378a67e0
          args:
            - "server"
            - "-config=/openbao/config/openbao.hcl"
          ports:
            - containerPort: 8200
            - containerPort: 8201
          env:
            - name: BAO_ADDR
              value: "http://127.0.0.1:8200"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - IPC_LOCK
          volumeMounts:
            - name: openbao-config-rw
              mountPath: /openbao/config
            - name: openbao-data
              mountPath: /openbao/data
      volumes:
        - name: openbao-config
          configMap:
            name: openbao-config
        - name: openbao-config-rw
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: openbao-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
