---
# Role metadata for rancher-fleet-argocd
galaxy_info:
  role_name: rancher-fleet-argocd
  author: ansible-runner
  description: Configure Rancher Fleet to install Argo CD
  license: MIT
  min_ansible_version: "2.14"
