apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-forward-auth-headers
  namespace: argocd
data:
  Host: authentik.cluster-duck.cloud
  X-Original-URL: $pass_access_scheme://$best_http_host$request_uri
  X-Original-Method: $request_method
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-forward-auth-headers
  namespace: gitea
data:
  Host: authentik.cluster-duck.cloud
  X-Original-URL: $pass_access_scheme://$best_http_host$request_uri
  X-Original-Method: $request_method
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-forward-auth-headers
  namespace: headlamp
data:
  Host: authentik.cluster-duck.cloud
  X-Original-URL: $pass_access_scheme://$best_http_host$request_uri
  X-Original-Method: $request_method
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-forward-auth-headers
  namespace: homepage
data:
  Host: authentik.cluster-duck.cloud
  X-Original-URL: $pass_access_scheme://$best_http_host$request_uri
  X-Original-Method: $request_method
