apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openbao-ui-internal
  namespace: openbao
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: openbao.mudazukai.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openbao
                port:
                  number: 8200
