title: Cluster Portal
headerStyle: boxedWidgets
statusStyle: "dot"
target: _self
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
layout:
  Cluster Operations:
    style: row
    columns: 2
  GitOps and Source:
    style: row
    columns: 2
  Secrets and Identity:
    style: row
    columns: 2
  Metrics and Alerts:
    style: row
    columns: 3
  Network and Delivery:
    style: row
    columns: 4
providers:
  longhorn:
    url: http://longhorn-frontend.longhorn-system.svc.cluster.local
