apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-cluster-config
data:
  EXTERNAL_DNS_DOMAIN_FILTER: 'example.services'
  GITEA_LOCAL_HOST: 'gitea.example.local'
  GITEA_PUBLIC_HOST: 'gitea.example.services'
  ARGOCD_LOCAL_HOST: 'argocd.example.local'
  ARGOCD_PUBLIC_HOST: 'argocd.example.services'
  OPENBAO_LOCAL_HOST: 'openbao.example.local'
  OPENBAO_PUBLIC_HOST: 'openbao.example.services'
  AUTHENTIK_LOCAL_HOST: 'authentik.example.local'
  AUTHENTIK_PUBLIC_HOST: 'authentik.example.services'
  AUTHENTIK_LEGACY_LOCAL_HOST: 'authentik.local'
  AUTHENTIK_FORWARD_AUTH_URL: 'http://authentik-server.authentik.svc.cluster.local:80/outpost.goauthentik.io/auth/nginx'
  AUTHENTIK_LOCAL_AUTH_SIGNIN: 'https://$host/outpost.goauthentik.io/start?rd=$scheme://$http_host$escaped_request_uri'
  AUTHENTIK_PUBLIC_AUTH_SIGNIN: 'https://$host/outpost.goauthentik.io/start?rd=$scheme://$http_host$escaped_request_uri'
  AUTHENTIK_AUTH_RESPONSE_HEADERS: 'Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid'
  AUTHENTIK_AUTH_SNIPPET: 'proxy_set_header X-Forwarded-Host $http_host;'
  HOMEPAGE_LOCAL_HOST: 'home.example.local'
  HOMEPAGE_PUBLIC_HOST: 'home.example.services'
  HEADLAMP_LOCAL_HOST: 'headlamp.example.local'
  HEADLAMP_PUBLIC_HOST: 'headlamp.example.services'
  REGISTRY_LOCAL_HOST: 'registry.example.local'
  REGISTRY_PUBLIC_HOST: 'registry.example.services'
