apiVersion: v1
kind: ConfigMap
metadata:
  name: rke2-ingress-nginx-controller
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  allow-snippet-annotations: "true"
  annotations-risk-level: Critical
