apiVersion: v1
kind: ConfigMap
metadata:
  name: ansible-cluster-config
data:
  ANSIBLE_RUNNER_IMAGE: 'registry.mudazukai.cloud/gitea-admin/ansible-runner:build-9a0fdc53e3ba8fc2'
  TAILSCALE_DOMAIN: 'armadillo-peacock.ts.net'
  TAILSCALE_CLUSTER_TAG: 'tag:cluster'
