apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-registry-creds
  namespace: ansible
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: gitea-registry-creds
    creationPolicy: Orphan
    deletionPolicy: Retain
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: >-
          {"auths":{"{{ .host }}":{"username":"{{ .username }}","password":"{{ .token }}","auth":"{{ printf "%s:%s" .username .token | b64enc }}"}}}
  dataFrom:
    - extract:
        key: apps/gitea/registry
