apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-user-sync
  namespace: ansible
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: tailscale-user-sync
    creationPolicy: Orphan
    deletionPolicy: Retain
  data:
    - secretKey: TAILSCALE_OAUTH_CLIENT_ID
      remoteRef:
        key: apps/ansible/tailscale
        property: oauth_client_id
    - secretKey: TAILSCALE_OAUTH_CLIENT_SECRET
      remoteRef:
        key: apps/ansible/tailscale
        property: oauth_client_secret
