apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argocd-audit-evidence
  namespace: compliance
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
