apiVersion: v1
kind: Secret
metadata:
  name: apprise-config
  namespace: observability
type: Opaque
stringData:
  apprise.yml: |
    version: 1
    # Add one or more Apprise notification URLs here.
    # Examples: https://github.com/caronc/apprise/wiki
    # - discord://...
    # - slack://...
    # - smtp://...
    urls: []
