apiVersion: v1
kind: ServiceAccount
metadata:
  name: apprise
  namespace: observability
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: apprise-openbao
  namespace: observability
spec:
  provider: openbao
  parameters:
    roleName: apprise
    objects: |
      - objectName: apprise.yml
        secretPath: secret/data/apps/observability/apprise
        secretKey: apprise_yml
