apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: apprise-config
  namespace: observability
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: apprise-config
    creationPolicy: Orphan
    deletionPolicy: Retain
    template:
      data:
        apprise.yml: "{{ .apprise_yml }}"
  data:
    - secretKey: apprise_yml
      remoteRef:
        key: apps/observability/apprise
        property: apprise_yml
