apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-repo-https
  namespace: argocd
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: argocd-repo-https
    creationPolicy: Orphan
    deletionPolicy: Retain
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        url: "{{ .url }}"
        username: "{{ .username }}"
        password: "{{ .password }}"
        type: git
  data:
    - secretKey: url
      remoteRef:
        key: apps/argocd/repository
        property: url
    - secretKey: username
      remoteRef:
        key: apps/argocd/repository
        property: username
    - secretKey: password
      remoteRef:
        key: apps/argocd/repository
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-repository-bootstrap
  namespace: argocd
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: argocd-repository-bootstrap
    creationPolicy: Orphan
    deletionPolicy: Retain
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        url: "{{ .url }}"
        username: "{{ .username }}"
        password: "{{ .password }}"
        type: git
        name: bootstrap-gitea
  data:
    - secretKey: url
      remoteRef:
        key: apps/argocd/repository
        property: url
    - secretKey: username
      remoteRef:
        key: apps/argocd/repository
        property: username
    - secretKey: password
      remoteRef:
        key: apps/argocd/repository
        property: password
